@host = http://localhost:8080
# GET
GET {{host}}/users/7

# INSERT
# POST {{host}}/users 
# content-type: application/json

# { 
#     "name": "Bob Brown",
#     "email": "bob@gmail.com",
#     "phone" : "97755755",
#     "password": "123456"
# }

#  DELETE
# DELETE {{host}}/users/3

# UPDATE
# PUT {{host}}/users/1
# content-type: application/json

# { 
#     "name": "Bob Brown",
#     "email": "bob@gmail.com",
#     "phone" : "97755755"
# }